#!/bin/bash
#========================================================================
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# This file is a part of the make OpenWrt for Amlogic s9xxx tv box
# https://github.com/ophub/amlogic-s9xxx-openwrt
#
# Description: Manage swap space for OpenWrt system
# Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-openwrt
#
# Command: openwrt-swap 1
# The input parameter unit is GiB, the default is 1
#
#=======================================================================
#
STEPS="[\033[95m STEPS \033[0m]"
INFO="[\033[94m INFO \033[0m]"
SUCCESS="[\033[92m SUCCESS \033[0m]"
OPTIONS="[\033[93m OPTIONS \033[0m]"
ERROR="[\033[91m ERROR \033[0m]"

# Output error message and abort script execution
error_msg() {
    echo -e "${ERROR} ${1}"
    exit 1
}

# Check disk
do_checkdisk() {
    # Find the partition where root is located
    ROOT_PTNAME="$(df -h /boot | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
    [[ -z "${ROOT_PTNAME}" ]] && error_msg "Unable to determine the root filesystem partition!"

    # Find the disk where the partition is located, supporting multi-digit partition numbers
    case "${ROOT_PTNAME}" in
    mmcblk?p[0-9]*)
        # Using sed to remove the trailing 'p' and all numbers
        # For example, mmcblk0p1 -> mmcblk0
        DISK_NAME=$(echo "${ROOT_PTNAME}" | sed -E 's/p[0-9]+$//')
        PARTITION_NAME="p"
        ;;
    [hsv]d[a-z][0-9]*)
        # Using sed to remove all trailing numbers
        # For example, sda1 -> sda
        DISK_NAME=$(echo "${ROOT_PTNAME}" | sed -E 's/[0-9]+$//')
        PARTITION_NAME=""
        ;;
    nvme?n?p[0-9]*)
        # Using sed to remove the trailing 'p' and all numbers
        # For example, nvme0n1p1 -> nvme0n1
        DISK_NAME=$(echo "${ROOT_PTNAME}" | sed -E 's/p[0-9]+$//')
        PARTITION_NAME="p"
        ;;
    *)
        error_msg "Unrecognized disk type: ${ROOT_PTNAME}!"
        ;;
    esac

    PARTITION_PATH="/mnt/${DISK_NAME}${PARTITION_NAME}4"
    available_space="$(df -Tk ${PARTITION_PATH} | grep '/dev/' | awk '{print $5}' | echo $(($(xargs) / 1024 / 1024)))"
    if [[ -z "$(echo "${available_space}" | sed -n "/^[0-9]\+$/p")" ]]; then
        error_msg "Target partition is unavailable, cannot determine remaining space."
    fi
    if [[ "${available_space}" -lt "${swap_gb}" ]]; then
        error_msg "Insufficient space: [ ${available_space} ] GiB available, [ ${swap_gb} ] GiB required for swap."
    fi

    SWAP_PATH="${PARTITION_PATH}/.swap"
    mkdir -p ${SWAP_PATH} && sync
    echo -e "${INFO} Creating [ ${swap_gb} ] GiB swap file in [ ${SWAP_PATH} ]."
}

# Delete current swap
delete_current_swap() {
    echo -e "${STEPS} Current swap size: [ ${1} ] MiB, removing..."
    current_swap_file="$(cat /proc/swaps | sed -n '$p' | awk '{print $1}' | echo $(xargs))"
    swapoff ${current_swap_file} 2>/dev/null && sync
    echo -e "${SUCCESS} Existing swap removed successfully!"
}

# Create new swap
create_the_swap() {
    echo -e "${STEPS} Creating new swap space..."
    ROOTFS_TYPE="$(df -hT ${SWAP_PATH} | tail -n1 | awk '{print $2}')"
    echo -e "${INFO} Swap size: [ ${swap_gb} ] GiB, partition type: [ ${ROOTFS_TYPE} ]. Please wait..."

    # create swapfile
    dd if="/dev/zero" of="${SWAP_PATH}/swapfile" bs="1024" count="$((1048576 * ${swap_gb}))" conv="fsync"
    chmod 600 ${SWAP_PATH}/swapfile
    mkswap ${SWAP_PATH}/swapfile
    swap_loopdev="$(losetup -f)"
    losetup ${swap_loopdev} ${SWAP_PATH}/swapfile
    swapon ${swap_loopdev}
    # Set up automatic mount at boot
    sed -i '/swapfile/d' /etc/fstab
    echo "${SWAP_PATH}/swapfile  none  swap  defaults  0  0" >>/etc/fstab

    sync && sleep 3
    echo -e "${INFO} Current swap status: \n$(cat /proc/swaps)"
    echo -e "${SUCCESS} Swap space created successfully!"
}

# Check swap
do_checkswap() {
    # Set the swap size in GiB
    my_swap_gb="${1}"
    format_gb="$(echo "${my_swap_gb}" | awk -F "." '{print $1}')"
    if [[ -n "$(echo "${format_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
        swap_gb="${format_gb}"
    else
        swap_gb="1"
    fi

    # Check disk
    do_checkdisk

    # manage swap
    current_swap="$(free -m | sed -n '$p' | awk '{print $2}' | echo $(xargs))"
    if [[ "${current_swap}" -ne "0" ]]; then
        delete_current_swap ${current_swap}
        create_the_swap ${swap_gb}
    else
        create_the_swap ${swap_gb}
    fi
    exit 0
}

echo -e "${STEPS} Welcome to the Swap Management Tool."
# Check script permission
[[ -x "/usr/sbin/openwrt-swap" ]] || error_msg "Please grant execution permission: [ chmod +x /usr/sbin/openwrt-swap ]"
# Check swap
do_checkswap "${@}"
