#!/bin/sh

# 赋予执行权限
chmod +x /usr/bin/leigod_sync.sh
chmod +x /etc/init.d/leigod_sync

# 启用服务 (创建一个 S99 的软链接)
/etc/init.d/leigod_sync enable
/etc/init.d/lighttpd enable


# lan设置
# 设置 LAN 口 IP 地址
uci set network.lan.ipaddr='10.0.0.2'

# 设置子网掩码
uci set network.lan.netmask='255.255.255.0'

# 设置 DNS (多个 DNS 用空格分开)
uci set network.lan.dns='223.5.5.5 1.1.1.1'

# 设置 IPv6 分配长度
uci set network.lan.ip6assign='64'

# --- 关键：物理接口与桥接设置 ---
# 如果你想强制指定 eth0 并不使用桥接 (br-lan)，取消下面几行的注释：
uci set network.lan.device='eth0'
# uci delete network.lan.type   # 删除桥接类型

# 如果你想保持默认的桥接模式 (推荐，兼容性更好)，但确保包含 eth0：
# 新版 OpenWrt (DSA 架构) 通常不需要手动指定 eth0，系统会自动识别
# 但为了保险，可以强制设置：
uci set network.lan.proto='static'

# 提交应用更改
uci commit network

# 重启网络服务 (可选，让设置立即生效，但在启动过程中通常不需要)
# /etc/init.d/network restart

exit 0